### ISSUE TITLE
New Repository for Spectral Library Format

### ISSUE THREAD

**Issue by ypriverol** [HUPO-PSI/SpectralLibraryFormat#1]
@edeutsch 

I have created the repository for the spectral library format, including:

- **examples** :  It will contain all the examples of the file formats and the legacy formats examples such as (MSP, splib, etc. )	
- **legacy-formats**: Legacy formats are the specifications of the previous legacy formats such as MSP, splib, etc. 
- **specification**: Specification contains all the information about the Spectral Library Specification. 

Regards 
Yasset

**Comment by ypriverol** [comment]
@jshofstahl @jshofstahl can anyone provides a spectral library for metabolomics in MSP or another type of file format.

**Comment by edeutsch** [comment]
Maybe one good example of a library/set of spectra for metabolomics would
be MassBank:



http://www.massbank.jp/SVN/OpenData/record/

http://www.massbank.jp/SVN/OpenData/record/IPB_Halle/PB000447.txt



I don’t know much about it, just bumbled into it a few days ago.



Eric







*From:* Yasset Perez-Riverol [mailto:notifications@github.com]
*Sent:* Tuesday, May 02, 2017 3:30 AM
*To:* HUPO-PSI/SpectralLibraryFormat
*Cc:* Eric Deutsch; Mention
*Subject:* Re: [HUPO-PSI/SpectralLibraryFormat] New Repository for Spectral
Library Format (#1)



@jshofstahl <https://github.com/jshofstahl> @jshofstahl
<https://github.com/jshofstahl> can anyone provides a spectral library for
metabolomics in MSP or another type of file format.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/HUPO-PSI/SpectralLibraryFormat/issues/1#issuecomment-298597808>,
or mute the thread

**Comment by ypriverol** [comment]
@edeutsch I have added the example files.
